version: "3.9"

services:
  client:
    build:
      context: reactjs
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    networks:
      - vanillanet

networks:
  vanillanet:
